services:
  devcontainer:
    image: alexjunk/emoncms
    volumes:
      - data:/data
      - ../:${EMONCMS_DIR}/modules/postprocess
    ports:
      - 8088:80
      - 8883:1883
    restart: always
volumes:
  data:
